### ISSUE TITLE
Problem during qr scan

### ISSUE THREAD

**Issue by tituwapro** [karmaisgreat/simple-whatsapp-bot#2]
I did all steps but when I opened whatapp web to scan the qr it didn't scan

**Comment by karmaisgreat** [comment]
People are using Heroku web logs to scan the QR Code, I recommend use Heroku CLI to scan the QR Code!

> heroku logs -a (your-app-name) --tail

Also make sure the postgresql database is created!

**Comment by Ayanokoji-Kiyotaka** [comment]
Even after using heroku CLI , WhatsApp us saying "Please use official WhatsApp website to scan the QR code

**Comment by karmaisgreat** [comment]
> Even after using heroku CLI , WhatsApp us saying "Please use official WhatsApp website to scan the QR code

Tell me about you device and are you using beta version or modded WhatsApp?
